registry:
 restart: always
 image: registry:2
 ports:
  — 5000:5000
 environment:
   REGISTRY_HTTP_TLS_CERTIFICATE: /cert/registry-cert.crt
   REGISTRY_HTTP_TLS_KEY: /cert/registry-cert.key
   REGISTRY_AUTH: htpasswd
   REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
   REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
 volumes:
  — /Users/hsmirnou/kubernetes/registry/data:/var/lib/registry
  — /Users/hsmirnou/kubernetes/registry/cert:/cert
  — /Users/hsmirnou/kubernetes/registry/auth:/auth
