apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: downward-api
  name: downward-api
spec:
  containers:
  - image: nginx
    name: downward-api
    resources: {}
    command:
      - sleep
      - "3600"

    volumeMounts:
    - mountPath: /data-mount
      name: podinfo
  volumes:
  - name: podinfo
    downwardAPI: 
      items:
      - path: metadata
        fieldRef:
          fieldPath: metadata.labels
 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
