apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-mem
  name: nginx-mem
spec:
  containers:
  - image: nginx
    name: nginx-mem
    resources: {}

    volumeMounts:
    - mountPath: /data-mount
      name: data
  volumes:
  - name: data
    emptyDir:
      medium: Memory
 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
