apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}

    volumeMounts:
    - mountPath: /data-mount
      name: data
  volumes:
  - name: data
    emptyDir: {}
 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
