apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-host-path
  name: nginx-host-path
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}

    volumeMounts:
    - mountPath: /data-mount
      name: data
  volumes:
  - name: data
    hostPath: 
      path: /tmp/data-ttest
 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
