kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: generic
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zones: eu-central-1a, eu-central-1b
  iopsPerGB: "10" 
  fsType: ext4
