kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: cluster-role-namespace-ro 
rules:
- apiGroups: ["*"] 
  resources: ["configmaps", "events", "namespaces"]
  verbs: ["watch", "get", "list"]