apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole
metadata:
  name: sa-role 
rules:
- apiGroups: ["extensions", "apps"] 
  resources:
  - deployments
  - replicasets
  - ingresses
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - namespaces
  - events
  verbs: ["get", "list", "watch"]
- apiGroups: [""] 
  resources:
  - pods
  - services
  - secrets
  - replicationcontrollers - persistentvolumeclaims - jobs
  - cronjobs
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding
metadata:
  name: sa-role-binding 
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole
  name: sa-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
#       system:serviceaccount:<namespace>:<serviceaccountname> 
  name: system:serviceaccount:chap8-domain1:chapter8-serviceaccount