---
apiVersion: v1
kind: Service
metadata:
  name: remote-host
  labels:
    app: remote-host
spec:
  ports:
    - port: 22
  selector:
    app: remote-host
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: remote-host
  name: remote-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote-host
  template:
    metadata:
      labels:
        app: remote-host
    spec:
      containers:
      - image: 050419950514/remote-host:v2
        name: remote-host
        volumeMounts:
          - mountPath: /var/data
            name: remote-host-persistent-volume-data
      volumes:
      - name: remote-host-persistent-volume-data
        persistentVolumeClaim:
          claimName: remote-host-data       
