kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: test2
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-028ec48bbe67a086b
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claimr
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-ebs
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claimr
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
         - mountPath: “/usr/share/nginx/html”
           name: task-pv-storage
