apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-2
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "0.3"
        memory: "200Mi"
      requests:
        cpu: "0.3"
        memory: "200Mi"