apiVersion: v1
kind: LimitRange
metadata:
  name: qos-for-namespace
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container