# for configMap have the same structure. Just use 'configMap' name instead 'secret'
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  app.conf: |
    target: stels
    dest: Kiev
    try: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    command: ["/bin/bash", "-c", "while : ;do cat /secret/username /secret/password; sleep 10; done"]
    volumeMounts:
      - name: projected-volume
        mountPath: /projected-volume
        readOnly: true
  volumes:
  - name: projected-volume
    projected:
      sources:
      - secret: 
         name: mysecret
         items: 
         - key: username
           path: username
         - key: password
           path: password
      - configMap:
         name: config-map
         items:
         - key: app.conf
           path: configmap 
  restartPolicy: Never
